dotdc/grafana-dashboards-kubernetes

- dashboards/k8s-views-global.json
Signed-off-by: David <davidcalvertfr@gmail.com>
- version bump
- Bumped version after @reefland fix 
- N/A
- N/A
> feat: bumped k8s-views-global.json version

- dashboards/k8s-views-global.json
- fix
- Use the node_exporter CPU metrics to get system level data.
- Fixes: https://github.com/dotdc/grafana-dashboards-kubernetes/issues/3
- ...
> Use node_exporter metrics for node CPU

- dashboards/k8s-views-global.json
- dashboards/k8s-views-nodes.json
Signed-off-by: David <davidcalvertfr@gmail.com>
- feat
- Fix & follow up of #16
> feat: use node metrics for cpu calc

- dashboards/k8s-views-pods.json
Signed-off-by: David <davidcalvertfr@gmail.com>
- feat
- reworked k8s-views-pods.json with ideas from #21
> feat: reworked k8s-views-pods.json with ideas from (#21)

- dashboards/k8s-views-global.json
- dashboards/k8s-views-namespaces.json
- dashboards/k8s-views-nodes.json
- dashboards/k8s-views-pods.json
#27
- fix 
- the color of some `Stat` panels was changed to `none`, to make it visible for users of Grafana light background
- #27
> fix: unreadable panels with light background

- dashboards/k8s-views-pods.json
Fix query on Network - Bandwidth panel
- fix
-
```
"expr": "- sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
```
```
"expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
```
- [issues/29](https://github.com/dotdc/grafana-dashboards-kubernetes/issues/29)
- ...
> Fix query on Network - Bandwidth panel

- dashboards/k8s-system-coredns.json
- fix
- Thanks much for the awesome dashboards! it works out of the box 🙏  This is a minor PR (use `=~` instead of `=`) to the DNS errors PromQL expression in the CoreDNS dashboard to make the chart work. Thanks! :-)
- ...
- ...
> fix dns errors promql expression

- dashboards/k8s-views-nodes.json
- fix
- Change instance variable selector
- #37
> Fix node dashboard on OKE

- dashboards/k8s-views-pods.json
- fix
- memory display bug in k8s-views-pods.json
- fixes #57
> fix: memory display bug in k8s-views-pods.json

- dashboards/k8s-views-nodes.json
- fix
- Added a missing `instance` label
- #68
> fix(k8s-views-nodes.json): missing instance label

- dashboards/k8s-views-nodes.json
- fix
- Removed the unused job variable in `k8s-views-nodes.json`
- fixes #71
> fix(k8s-views-nodes.json): removed unused job var

- dashboards/k8s-addons-trivy-operator.json
-  feat
- add filter on Detaillled CVE vulnerabilities table 
- ...
- ...
> Make Detaillled CVE vulnerabilities table filterable

- dashboards/k8s-views-namespaces.json
- dashboards/k8s-views-nodes.json
- dashboards/k8s-views-pods.json
- feat
- Added the ability to filter on cluster in ns, nodes and pods views when it's in use
- Linked to #15
> feat: added cluster var in ns, nodes and pods views

- dashboards/k8s-system-coredns.json
- fix
- Ability to filter `k8s-system-coredns.json` by `job`.
- fixes #70
> fix(k8s-system-coredns.json): ability to filter on job

- dashboards/k8s-views-namespaces.json
- dashboards/k8s-views-nodes.json
- dashboards/k8s-views-pods.json
- fix
- filter resources by cluster label
> fix: filter resources by cluster label

- dashboards/k8s-system-coredns.json
- fix
- Change job value from core-dns to $job variable
- https://github.com/dotdc/grafana-dashboards-kubernetes/issues/70
- ...
> Fix: change job value from core-dns to $job variable.

- dashboards/k8s-addons-prometheus.json
- dashboards/k8s-system-api-server.json
- dashboards/k8s-system-coredns.json
- dashboards/k8s-views-global.json
- dashboards/k8s-views-nodes.json
- fix
- Fixes all datasources to use the variable `${data_source}` so it works across deployments
- Similar fix for all other dashboards as done in #95
> Fix all dashboard datasources

- .pre-commit-config.yaml
- dashboards/k8s-views-namespaces.json
- fix
- Removed the container label selector from the created_by_name variable.
- fixes https://github.com/dotdc/grafana-dashboards-kubernetes/issues/116
> fix: created_by_name var in kubernetes-views-namespaces

- dashboards/k8s-addons-prometheus.json
- dashboards/k8s-addons-trivy-operator.json
- dashboards/k8s-system-coredns.json
- dashboards/k8s-views-namespaces.json
- dashboards/k8s-views-pods.json
- fix
- Using a `.*` regex for `all` options in dashboards following #131
> fix: use regex wildcard for all options

- dashboards/k8s-views-nodes.json
- dashboards/k8s-views-pods.json
- fix
- When having several clusters, the cluster var is missing when clicking a pod, which leads to a non-working tab.
Thanks for this repo! let me know if anything else is needed!
> Update data links to include required vars to not break drill down

- dashboards/k8s-views-nodes.json
Fixes bug https://github.com/dotdc/grafana-dashboards-kubernetes/issues/150
> fix parsing bug: unknown escape sequence U+002E '.'

- dashboards/k8s-addons-trivy-operator.json
- fix
- Corrects a simply typo in a panel name
> fix: Spelling mistake CVE vulns in panel
