dotdc/grafana-dashboards-kubernetes

dashboards/k8s-system-api-server.json
- fix 
- API Server - Errors by Instance selects 5xx error  with "=",  it should be "=~"
-  API Server - Errors by Verb  selects 5xx error  with "=",  it should be "=~"
- ...
- ...
=> fix| apiserver_request_total code 5xx match with =~

dashboards/k8s-views-global.json
Fixed 2 graphs showing incorrect numbers for pods.
- fix
- Running pod counts are incorrect.  Changed to be based on phase="running"
- none
- The original values for me were reporting 88 running pods, but K8s LENS reported 83 pods.   When I switched to phase="running" I got a matching 83 pods.   Possible what you were using also picks up "jobs" as I had 5 completed jobs which gives the "88".
- I was unable to test this version directly as I have other customizations for my K3s / containerd but wanted to pass this correction back to you.
=> Fixed Running Pod Count based on phase

dashboards/k8s-views-nodes.json
- fix
- Updated node variable to source node name information from `kube_node_info` instead of `node_uname_info`. On AKS deployments `node_uname_info` returns node name with capitalised last character (ie, `aks-a12bcdef-0123456789-vmss00006H`), but at the same time node name provided by `kube_node_info` is lower cased (ie `aks-a12bcdef-0123456789-vmss00006h`). As result some dashboard panels do not visualise information correctly.
- This PR partially addresses #3
=> Update variable query string for nodes dashboard

kustomization.yaml
feat
By removing the default value, one can copy the argocd.yaml file into one's own git repository, refer directly to this repo on Github (thus benefiting from updates), /and/ pick a custom namespace to target.
If the kustomization.yaml file contains a target namespace already, there seems to be [no straightforward way](https://github.com/kubernetes-sigs/kustomize/issues/880) to override this from ArgoCD.
=> Remove default kustomization namespace

dashboards/k8s-views-nodes.json
- feat
- added drill down link from Node dashboard to Pod dashboard. Clicking on pod in list of pods now brings you directly to pod dashboard for this pod
=> add link from node dashboard to pods

dashboards/k8s-views-global.json
- fix 
Percentage for cluster memory utilization didn't have a decimal limit while other percentage on this dashboard are set to 2.
I doubt that this was intented so here's a fix.
- No open issues
- Let me know if something need to be added to merge this PR
=> set percentage 2 decimals long for memory usage

dashboards/k8s-system-coredns.json
- feat
- Added heatmaps for CoreDNS histogram metrics that were previously not being visualized.
- N/A
- We don't use kube-prometheus-stack, so this is not validated to work there. But it does work with our CoreDNS deployment, which works with the rest of this dashboard.
=> Add heatmaps for CoreDNS histogram metrics

dashboards/k8s-system-coredns.json
The method for taking the average of a histogram metric is documented here:
https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations
- fix
Fix the PromQL expression for CoreDNS request average packet size. The value being shown was a meaningless value: the average across all CoreDNS servers of the sum of all request packet sizes in each server over `$__rate_interval`. This is not the average size of packets received by CoreDNS servers over `$__rate_interval`, which I imagine is what was intended.
The old query, explained another way:
- `coredns_dns_request_size_bytes_sum` is the sum of sizes of all request packets ever received.
- `rate(coredns_dns_request_size_bytes_sum[$__rate_interval])`, by itself, is the per-second rate of increase of the sum of sizes of request …
=> Fix PromQL epxression for coredns average packet size

README.md
- docs
- Following the discussion on #44, this PR adds a workaround to relabel the output of the node-exporter. This fix works on the lab setup provided in the issue, but we still need to test it on other scenarios.
- #44
=> doc: add workaround to issue #44

dashboards/k8s-views-global.json
- fix
- The metric `up{job="node-exporter"}` does not exist when using Grafana Agent. Counting `kube_node_info` should be agnostic and more reliable.
- Fixes #46
- N/A
=> count nodes by kube_node_info, instead of node-exporter jobs

dashboards/k8s-views-global.json
- fix
- there's a bug (which at least fires up with my setup (VictoriaMetrics), that a label selector is written with a single quote which returns no result.
concretely: 
```
sum(kube_pod_status_phase{phase='Running'}) # doesn't work, unescaped single quote
sum(kube_pod_status_phase{phase=\"Running\"}) # does work, with escaped quotes
```
=> fix(k8s-views-global): correctly escape quote

dashboards/k8s-addons-trivy-operator.json
- feat
- It makes colors in trivy-operator dashboard more consistent over the different panels (e.g. in timeseries critical was green)
- It also changes colors for
- critical = dark red
- high =red
- medium = orange
- low = yellow
=> Make trivy operator dashboard colors more consistent

dashboards/k8s-views-global.json, dashboards/k8s-views-namespaces.json, dashboards/k8s-views-pods.json
- fix
- Replaced the `unit` label with `resource` for `kube_pod_container_resource_{requests|limits}`.
- This should fix graph values when `unit=byte` and `resource=ephemeral_storage`.
- https://github.com/dotdc/grafana-dashboards-kubernetes/issues/54
=> fix: use resource label instead of unit

dashboards/k8s-system-api-server.json
without the fix, the dashboards show the cumulative duration of all buckets, which doesn't make much sense. (we plot `sum by (instance)` of buckets, and there are ~10 buckets (`le="0.05", le="0.1", ..., le="+Inf"`). this doesn't represent the latency of the API server.
with the fix, we divide the total duration by the number of requests, which yields the average latency. note that we could also have used `_duration_seconds_bucket{le="+Inf"}` instead of `duration_seconds_sum`
- fix
before:
after:
=> fix(apiserver-duration): compute average of duration

dashboards/k8s-addons-trivy-operator.json
- fix
- Using datasource var instead of hardcoded
- https://github.com/dotdc/grafana-dashboards-kubernetes/issues/65
- ...
=> fix(k8s-addons-trivy-operator.json): data source vars

dashboards/k8s-views-pods.json
- fix
- Added the ability to filter using the `job` label to fix some queries in `k8s-views-pods.json` for users that have multiple values in the `job` label.
- fixes #75
=> fix: multiple job values in pods view

dashboards/k8s-views-global.json
- feat
- Added the ability to filter on cluster when it's in use
- Linked to #15
=> feat(k8s-views-global.json): added cluster variable

dashboards/k8s-views-global.json, dashboards/k8s-views-namespaces.json, dashboards/k8s-views-nodes.json
- fix
- Used `Last *` on most lcd/gauge to be more consistent
- Fixes #88
=> fix: lcd/gauge calculations on global,ns,nodes

dashboards/k8s-views-global.json, dashboards/k8s-views-nodes.json
Fixes: #80
- fix
- Total CPU usage is now calculated based on all non-idle CPU modes. This is needed to prevent reporting negative values.
- #80
- https://www.tigera.io/learn/guides/prometheus-monitoring/prometheus-metrics/#CPU-Usage
=> fix: match all non-idle cpu modes when calculating total cpu usage

dashboards/k8s-addons-trivy-operator.json
- fix
- To fix the Trivy dashboard
- #94 
- ...
=> Fix trivy-dashboard datasource for variable.

dashboards/k8s-views-global.json, dashboards/k8s-views-namespaces.json, dashboards/k8s-views-nodes.json
- chore
- Just an import and export of the dashboards json via export function.
- Fixes #97 
- Reduces unnecessary diffs in a future PR
=> Re-Import Global, Namespace and Nodes

dashboards/k8s-views-global.json
- feat
- Added queries for windows nodes
- #79 
- Let me know, if you need access to an hybrid cluster
=> feat(k8s-views-global): Windows node support

dashboards/k8s-system-coredns.json
- fix
- Added datasource for the `job` variable in CoreDNS dashboard. It fixes CoreDNS dashboard if Grafana has multiple datasources
=> fix(k8s-system-coredns): add datasource for the job variable

dashboards/k8s-system-api-server.json
Adding compatibility with default scrape_configs:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L783
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L293
=> Adding compatibility with default scrape_configs

dashboards/k8s-system-api-server.json
Fix: #124
- fix
- percentage should within range `0-100`.
- #124
Tested locally,
=> fix: incorrect CPU utilization display

dashboards/k8s-views-pods.json
- fix
- Added `id` to group by for cpu/memory usage. When pod restarts the prometheus metrics for old and new pod sometimes overlap, creating spike in memory and cpu usage when 2 metrics are sumed together. Plotting then the incorectly high values which may be used to set up pod resources and limits incorrectly. See added screenshot where red and yellow lines are slightly overlapping which would cause spike without `id`.
=> fix: pod cpu/memory usage metrics grouped by id as well

dashboards/k8s-views-pods.json
- fix 
`pod` variable could contain thousands of options in some environments. Selecting `all` options would mean dashboard will include all of them into the PromQL query and potentially cause issues on processing.
Switching to wildcard `.*` instead will prevent sending huge queries to database and dashboard will continue to work for any environment.
fixes https://github.com/dotdc/grafana-dashboards-kubernetes/issues/129
=> views/pods: use wildcard for `all` option in `pod` variable

dashboards/k8s-views-namespaces.json
fix
All other filters use a custom all value as it's much more efficient than constructing a query with every single created_by value. It also prevents queries from becoming too long and rejected by Prometheus.
#146
- ...
=> fix(k8s-views-namespaces): use custom all value for created_by filter

dashboards/k8s-system-coredns.json
- fix
- Updated PromQL expressions in the `k8s-system-coredns.json` dashboard to replace deprecated CoreDNS metrics (`coredns_forward_requests_total` and `coredns_forward_responses_total`) with their recommended equivalents (`coredns_proxy_request_duration_seconds_count` with the label `proxy_name="forward"`).  
- This fixes issues caused by obsolete metrics and ensures compatibility with recent CoreDNS versions.  
- The change aligns with the project scope and is compatible with kube-prometheus-stack.
- Fixes missing data in the "CoreDNS - Total Forward Requests" and "CoreDNS - DNS Errors" graphs.
=> fix(k8s-system-coredns.json): replace deprecated CoreDNS metrics with coredns_proxy_equivalents
